### PR TITLE
Add Metamask support

### PR DESCRIPTION
**Pull request by leetdev**
Refactored frontend application to integrate with Metamask to fetch addresses and make WBGL transfers. Removes a lot of tedium from the bridging process, such as having to enter all addresses manually and generating signatures.

Deployment note: I've added `REACT_APP_TITLE` as an environment variable that contains the app title (used in both HTML title tag as well as app header). This needs to be present when building the production bundle. Also, `NODE_ENV` needs to be set to `production`, otherwise the app will be running on testnet.

### CODE REVIEW

**Comment by leetdev** [comment]
I've set up a [https://bitgesell-bridge.ultraleet.net/](staging server) for this app that contains all my latest developments. This way, the changes in this PR, for instance, can be tested out before they are approved. Note: it is currently configured to use Ethereum Ropsten, BSC Testnet, and BGL Mainnet. I plan to work on setting up CI and automated deployments next, as well as setting up a test suite for the frontend app.

**Comment by alekcangp** [comment]
Also, you can use BGL testnet: 
Explorer: https://testnet.bglnode.online/
Wallet: wallet.bglnode.online
BGL faucet: https://bglnode.online/
API: https://api.bglnode.online/

**Comment by leetdev** [comment]
@alekcangp Does Bitgesell core support connecting to this testnet? The bridge runs its own core client. If testnet is supported by core, do you know when (which version) it was added?

**Comment by alekcangp** [comment]
@leetdev 
For 0.1.8
Yes, it supports, but now, you need  to edit BGL.conf file: 
`[test]
addnode=164.132.216.58
addnode=164.132.216.61
addnode=77.91.69.182
minimumchainwork=0xff ` 

I think the team would add testnet config to the source code in a new build. https://discord.com/channels/745922397349347418/786136696088428574/1001408431493763102

For 0.1.7
I have checked it and run succesfully Bitgesell core 0.1.7 testnet `206.54.190.212` (https://testnet.bglnode.online/peers), but you need copy folder `.BGL/testnet3/blocks` from 0.1.8 to 0.1.7. I have attached.



[blocks.zip](https://github.com/BitgesellOfficial/wbgl-bridge/files/9437826/blocks.zip)

**Comment by alekcangp** [comment]
@leetdev 
For 0.1.8
Yes, it partially supports, you need  to edit BGL.conf file: 
`[test]
addnode=164.132.216.58
addnode=164.132.216.61
addnode=77.91.69.182
minimumchainwork=0xff ` 

I think the team would add testnet config to the source code in a new build. https://discord.com/channels/745922397349347418/786136696088428574/1001408431493763102

For 0.1.7
I have checked it and run succesfully Bitgesell core 0.1.7 testnet `206.54.190.212` (https://testnet.bglnode.online/peers), but you need copy folder `.BGL/testnet3/blocks` from 0.1.8 to 0.1.7. I have attached
[blocks.zip](https://github.com/BitgesellOfficial/wbgl-bridge/files/9437893/blocks.zip)

or wait a new build with fully wallet and testnet support.

**Comment by van-orton** [comment]
Indeed, new build 0.1.9 would hopefully contain the testnet nodes.
This PR has been reviewed and merged to code currently used in production for bridge. Merging this to main branch.

**Pull request merged**
